Many script changes I was too lazy to record

diff --git a/git-get-mr b/git-get-mr
--- a/git-get-mr
+++ b/git-get-mr
@@ -7,11 +7,30 @@ function _http_get {
 	curl --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" $url 2>/dev/null | jq -r "$jq_filter"
 }
 
+function _dependancy {
+	command_name=$1
 
-GITLAB_API_BASE_URL=$(git remote get-url origin | sed -r 's_^\s*(https?://)\w+@([a-zA-Z0-9\.]+).*$_\1\2/api/v4_')
+	if ! command -v "$command_name" >/dev/null 2>&1; then
+		echo "'$command_name' required but not found"
+		exit 1
+	fi
+} 
+
+_dependancy "jq"
+_dependancy "pass"
+
+if [[ $# -eq 0 ]]; then
+	commit_hash=$(git log -1 --pretty=format:%h)
+elif [[ $# -eq 1 ]]; then
+	commit_hash=$1
+else
+	echo "Invalid arguments"
+	exit 1
+fi
+
+GITLAB_API_BASE_URL=$(git remote get-url origin | sed -r 's_^\s*(https?://)(\w+@)?([a-zA-Z0-9\.]+)/.*$_\1\3/api/v4_')
 GITLAB_PRIVATE_TOKEN=$(pass show gitlab-private-token)
 
-commit_hash=$1
 repo_name=$(basename $(git rev-parse --show-toplevel))
 
 gitlab_repo_id=$(_http_get \
